{
	"document": [
		{
			"platform": "OpenAPI",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/metadata.json",
			"id": "557e3530-45a9-4fab-bf12-d9effb2a6102",
			"queryName": "Global Server Object Uses HTTP",
			"severity": "MEDIUM",
			"category": "Encryption",
			"descriptionText": "Global server object URL should use 'https' protocol instead of 'http'",
			"descriptionUrl": "https://swagger.io/specification/#server-object"
		},
		{
			"components": {
				"exampleSecurity": {
					"type": "https"
				}
			},
			"id": "daeff7a5-14a1-4aa3-842b-29db1b04a738",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/negative1.json",
			"openapi": "3.0.0",
			"info": {
				"title": "Simple API Overview",
				"version": "1.0.0"
			},
			"servers": [
				{
					"description": "Development server",
					"url": "https://development.gigantic-server.com/v1"
				},
				{
					"description": "Staging server",
					"url": "https://staging.gigantic-server.com/v1"
				},
				{
					"description": "Production server",
					"url": "https://api.gigantic-server.com/v1"
				}
			],
			"paths": {
				"/": {
					"get": {
						"operationId": "listVersionsv2",
						"responses": {
							"200": {
								"content": {
									"application/json": {
										"examples": {
											"foo": {
												"value": {
													"versions": [
														{
															"id": "v2.0",
															"links": [
																{
																	"href": "http://127.0.0.1:8774/v2/",
																	"rel": "self"
																}
															],
															"status": "CURRENT",
															"updated": "2011-01-21T11:33:21Z"
														}
													]
												}
											}
										}
									}
								},
								"description": "200 response"
							}
						},
						"summary": "List API versions"
					}
				}
			},
			"security": [
				{
					"exampleSecurity": []
				}
			]
		},
		{
			"paths": {
				"/": {
					"get": {
						"operationId": "listVersionsv2",
						"summary": "List API versions",
						"responses": {
							"200": {
								"description": "200 response",
								"content": {
									"application/json": {
										"examples": {
											"foo": {
												"value": {
													"versions": [
														{
															"links": [
																{
																	"href": "http://127.0.0.1:8774/v2/",
																	"rel": "self"
																}
															],
															"status": "CURRENT",
															"updated": "2011-01-21T11:33:21Z",
															"id": "v2.0"
														}
													]
												}
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"security": [
				{
					"exampleSecurity": []
				}
			],
			"components": {
				"exampleSecurity": {
					"type": "https"
				}
			},
			"id": "b6a03fc5-5e7a-43ef-8120-dbe56d1815b7",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/negative2.yaml",
			"openapi": "3.0.0",
			"info": {
				"version": "1.0.0",
				"title": "Simple API Overview"
			},
			"servers": [
				{
					"url": "https://development.gigantic-server.com/v1",
					"description": "Development server"
				},
				{
					"url": "https://staging.gigantic-server.com/v1",
					"description": "Staging server"
				},
				{
					"description": "Production server",
					"url": "https://api.gigantic-server.com/v1"
				}
			]
		},
		{
			"id": "707e3a27-6c12-475c-bec5-7278115c179e",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive1.json",
			"openapi": "3.0.0",
			"info": {
				"title": "Simple API overview",
				"version": "1.0.0"
			},
			"servers": [
				{
					"description": "Development server",
					"url": "https://development.gigantic-server.com/v1"
				},
				{
					"description": "Staging server",
					"url": "http://staging.gigantic-server.com/v1"
				}
			],
			"paths": {
				"/": {
					"get": {
						"operationId": "listVersionsv2",
						"responses": {
							"200": {
								"content": {
									"application/json": {
										"examples": {
											"foo": {
												"value": {
													"versions": [
														{
															"id": "v2.0",
															"links": [
																{
																	"href": "http://127.0.0.1:8774/v2/",
																	"rel": "self"
																}
															],
															"status": "CURRENT",
															"updated": "2011-01-21T11:33:21Z"
														}
													]
												}
											}
										}
									}
								},
								"description": "200 response"
							}
						},
						"summary": "List API versions"
					}
				}
			}
		},
		{
			"openapi": "3.0.0",
			"info": {
				"title": "Simple API overview",
				"version": "1.0.0"
			},
			"servers": [
				{
					"url": "https://development.gigantic-server.com/v1",
					"description": "Development server"
				},
				{
					"url": "http://staging.gigantic-server.com/v1",
					"description": "Staging server"
				}
			],
			"paths": {
				"/": {
					"get": {
						"summary": "List API versions",
						"responses": {
							"200": {
								"description": "200 response",
								"content": {
									"application/json": {
										"examples": {
											"foo": {
												"value": {
													"versions": [
														{
															"links": [
																{
																	"href": "http://127.0.0.1:8774/v2/",
																	"rel": "self"
																}
															],
															"status": "CURRENT",
															"updated": "2011-01-21T11:33:21Z",
															"id": "v2.0"
														}
													]
												}
											}
										}
									}
								}
							}
						},
						"operationId": "listVersionsv2"
					}
				}
			},
			"id": "8736fa84-8667-4065-99b1-4770f3c01e7b",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive2.yaml"
		},
		{
			"paths": {
				"/": {
					"get": {
						"operationId": "listVersionsv2",
						"summary": "List API versions",
						"responses": {
							"200": {
								"description": "200 response",
								"content": {
									"application/json": {
										"examples": {
											"foo": {
												"value": {
													"versions": [
														{
															"updated": "2011-01-21T11:33:21Z",
															"id": "v2.0",
															"links": [
																{
																	"rel": "self",
																	"href": "http://127.0.0.1:8774/v2/"
																}
															],
															"status": "CURRENT"
														}
													]
												}
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"security": [],
			"id": "1f7bc703-91ce-4568-9dc1-a8511bd64150",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive3.yaml",
			"openapi": "3.0.0",
			"info": {
				"title": "Simple API overview",
				"version": "1.0.0"
			}
		},
		{
			"line": 13,
			"filename": "positive1.json",
			"id": "189340e1-4ac2-433d-8529-2f749a15ac4f",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive_expected_result.json",
			"queryName": "Global Server Object Uses HTTP",
			"severity": "MEDIUM"
		},
		{
			"queryName": "Global Server Object Uses HTTP",
			"severity": "MEDIUM",
			"line": 8,
			"filename": "positive2.yaml",
			"id": "15af39f1-885d-426b-b65f-0b7fb66fd7df",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive_expected_result.json"
		},
		{
			"filename": "positive3.yaml",
			"id": "3949e074-768c-4336-834f-b31f9172be84",
			"file": "/home/reigota/kics/assets/queries/openAPI/global_server_uses_http/test/positive_expected_result.json",
			"queryName": "Global Server Object Uses HTTP",
			"severity": "MEDIUM",
			"line": 1
		}
	]
}
